name = "backend"
main = "src/index.ts"
compatibility_date = "2025-01-24"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMGY3YmNiZmEtMzk0Mi00Yjc0LTgwNmUtNjNjYmM2ZmE3N2Q5IiwidGVuYW50X2lkIjoiMTkwN2I3ZDA2ODJlMTY5MzY4ODkwNjdlOWJlZjI2Njk0MGZiNWMzOWQ3YmYxMmYxZmIxYjk4MDYyMDgxYzBlOSIsImludGVybmFsX3NlY3JldCI6IjQxMDQ1OThhLWY2NDctNDQwYi1hZDIyLWMzNTExOTU2Mjg2OSJ9.24HcEf9seMksQl7zq3G44Q2feaghXy8Tesj-9Qo3acM"

JWT_SECRET = "secret"